### ISSUE TITLE
С 35 урока не переходит на 36

### ISSUE THREAD

**Issue by Leronio** [hexlet-basics/exercises-html#109]
НЕ переходит с 35 урока на 36

**Comment by PlugIN73** [comment]
Спасибо. Поправлю в течение 5 минут.

**Comment by PlugIN73** [comment]
Исправил. Старая ссылка перестала работать. Перейдите в урок со страницы https://ru.code-basics.com/languages/html
Такая же проблема возможна в других уроках. Сейчас их тоже поправлю
