### ISSUE TITLE
Ошибка <ol> в 27 уроке HTML: Чекбокс

### ISSUE THREAD

**Issue by MarcusSten** [hexlet-basics/exercises-html#110]
Добрый день. Обучаясь обнаружил ошибку в 27 уроке:

Ошибка <ol> в 27 уроке HTML: Чекбокс

<span>
<p>Для создания связи <code class="prettyprint">label</code> с <code class="prettyprint">input</code> тоже существует два способа:</p>
--
  |  
  | <ol>
  | <li>Связь по <code class="prettyprint">id</code>. Для этого необходимо задать уникальный <code class="prettyprint">id</code> для <code class="prettyprint">input</code> и связать <code class="prettyprint">label</code> с чекбоксом с помощью атрибута <code class="prettyprint">for</code>.</li>
  | </ol>
  |  
  | <pre><code class="prettyprint lang-html">&lt;form&gt;
  | &lt;input id=&quot;html&quot; type=&quot;checkbox&quot;&gt;
  | &lt;label for=&quot;html&quot;&gt;Хочу изучать HTML&lt;/label&gt;
  | &lt;/form&gt;
  | </code></pre>
  |  
  | <ol>
  | <li>Вложить <code class="prettyprint">input</code> внутрь тега <code class="prettyprint">label</code>. При этом указание уникального <code class="prettyprint">id</code> не требуется.</li>
  | </ol>
</span>

В итоге у вас два раздельных списка, отображающихся с цифрой "1".

**Comment by Psixodelik** [comment]
Заменил на простой маркированный список :) Спасибо
