### ISSUE TITLE
"Съехавшее" форматирование в уроке 23 HTML: Viewport

### ISSUE THREAD

**Issue by pymerseme** [hexlet-basics/exercises-html#183]
В 23 уроке связанном с Viewport не "съехавшее" форматирование, возможно связано с тем, что у вас сначала идёт заголовок 3 уровня, а потом второго. В уроках, с 1 по 32 заголовки идут от старшего к младшему и начинаются всегда с заголовка второго уровня. В английской версии такая же ситуация.

Проверьте, пожалуйста.

![Screenshot 2023-04-16 at 23-35-48 Viewport HTML](https://user-images.githubusercontent.com/43650132/232341295-09ce9f53-d495-4f23-a3d6-57db13d4558f.png)

**Comment by ashikov** [comment]
Спасибо! Исправил. Скоро задеплою.
