### ISSUE TITLE
Случайно сломал первый урок по формам в курсе HTML

### ISSUE THREAD

**Issue by IsUnavailable** [hexlet-basics/exercises-html#55]
Случайно выяснил, что если в решение первого урока по формам (урок №25), в решение вставить кусок кода приведённый ниже, а потом нажать на кнопку на получившейся форме, то с содержимым `div` с ` id="basics-lesson-container"` произойдёт ровно то, что написано на кнопке С:

Бесовской код
```
<form action="/people">
  <button>Низвергнуть до атомов</button>
</form>
```

**Comment by IsUnavailable** [comment]
В принципе, это похоже не зависит от конкретного урока.

**Comment by Psixodelik** [comment]
Тут идёт прямое выполнение кода, который вы указываете :) В принципе ничего страшного
