### ISSUE TITLE
Пробел из ниоткуда между тегами span (курс html)

### ISSUE THREAD

**Issue by jelka2008** [hexlet-basics/exercises-html#57]
В уроке 24 было предложено поэкспериментировать с тэгом span.
В результате код:
    `<span>12</span><span>34</span> `
отрендерился в консоли как
    `1234`
Но после переноса 2-го тега на новую строку:
```
    <span>12</span>
    <span>34</span>
```
Результатом стало:
    `12 34`

Исправьте пожалуйста

**Comment by Psixodelik** [comment]
Здравствуйте

Браузеры и обработают перенос именно таким способом. Вы можете попробовать на любой странице воспроизвести такой эффект
