### ISSUE TITLE
HTML для начинающих на сайте ru.code-basics.com. Ошибка в принятии задания урока №36.

### ISSUE THREAD

**Issue by BentonFraizer** [hexlet-basics/exercises-html#64]
Некорректно принимается задание. 
Задание звучит следующим образом: "Создайте разметку «шапки» сайта. Расположите внутри картинку и маркированный список из двух ссылок".
Но если мы просто создадим маркированный список из двух элементов БЕЗ ссылок внутри, то задание всё равно будет принято.

**Comment by Psixodelik** [comment]
Добавил ещё тест. Спасибо
