### ISSUE TITLE
41 Укрок, ошибка проверки наличия Aside

### ISSUE THREAD

**Issue by pogorv12** [hexlet-basics/exercises-html#65]
Добрый день!

На 41 уроке не работает проверка, не находит тэг Aside.

**Код**
```
<header>
    <img src="/logo.png" alt="Логотип"> <!-- Логотип сайта -->
    <nav> <!-- Меню -->
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/about">О нас</a></li>
        </ul>
    </nav>
</header>

<aside>
    sdf
</aside>

<main>

    <section class="more">
          <h2>Читайте также</h2>

          <article class="article-block">
              <h3>Услуга 3</h3>
              <p>Описание новой услуги</p>
              <a href="#">Ссылка на услугу</a>
          </article>

          <article class="article-block">
              <h3>Услуга 4</h3>
              <p>Описание новой услуги</p>
              <a href="#">Ссылка на услугу</a>
          </article>
    </section>
</main>

```

**Ошибка**

> /usr/lib/node_modules/@github/query-selector/dist/index.umd.js:93
>     throw new QueryError("Element not found: <".concat(klass.name, "> ").concat(selectors));
>     ^
> 
> QueryError: Element not found: <HTMLElement> aside
>     at query (/usr/lib/node_modules/@github/query-selector/dist/index.umd.js:93:11)
>     at /exercises-html/modules/70-semantics/70-aside/test.js:26:17
>     at test (/exercises-html/src/tests.js:14:5)
>     at Object.<anonymous> (/exercises-html/modules/70-semantics/70-aside/test.js:3:1)
>     at Module._compile (internal/modules/cjs/loader.js:1201:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
>     at Module.load (internal/modules/cjs/loader.js:1050:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:938:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   framesToPop: 1
> }

**Comment by Psixodelik** [comment]
Здравствуйте

Обратите внимание на то, что aside является уникальным для страницы. Значит его можно расположить в другом месте.
